export const GET_PEGAWAI = 'GET_PEGAWAI';
export const GET_SINGLE_PEGAWAI = 'GET_SINGLE_PEGAWAI';
export const UPDATE_PEGAWAI = 'UPDATE_PEGAWAI';
export const DELETE_PEGAWAI = 'DELETE_PEGAWAI';
export const CREATE_PEGAWAI = 'CREATE_PEGAWAI';
export const GET_PROVINSI = 'GET_PROVINSI';